name: product_variant_option
properties:
  - name: uuid
    type: string
  - name: product_option_label
    type: string
  - name: product_option_values
    type: array
  - name: product_uuid
    type: string