name: product_variant
properties:
  - name: uuid
    type: string
  - name: product_uuid
    type: string
    # belongs_to: modules/insites_ecommerce/product
  - name: product_image
    type: upload
  - name: product_sku
    type: string
  - name: stock_level
    type: integer
    default_value: 0
  - name: regular_price
    type: float
    default_value: 0
  - name: cost_price
    type: float
    default_value: 0
  - name: compare_at_price
    type: float
    default_value: 0
  - name: sale_price
    type: float
    default_value: 0
  - name: is_on_sale
    type: boolean
    default_value: false
  - name: is_fixed_tax_amount
    type: boolean
    default_value: false
  - name: tax_amount
    type: float
    default_value: 0
  - name: freight_amount
    type: float
    default_value: 0
  - name: is_free_shipping
    type: boolean
    default_value: false
  - name: width
    type: float
    default_value: 0
  - name: length
    type: float
    default_value: 0
  - name: height
    type: float
    default_value: 0
  - name: weight
    type: float
    default_value: 0
  - name: product_options
    type: array